apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdhr-scanner-output
  labels:
    app: hdhr-scanner
    version: "3.0"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdhr-scanner-logs
  labels:
    app: hdhr-scanner
    version: "3.0"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
